### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by dmclain** [depop/sentry-pagerduty#3]
This code doesn't have an explicit license, which makes it more difficult to contribute/use. Please consider something like the MIT license.

**Comment by davedash** [comment]
Agreed, would love to use this and fix bugs.

http://choosealicense.com/

**Comment by cartisan** [comment]
Hey Depop, that's some of the code I've written during during summer '13. I'd love to see it in the wild!
If it doesn't bother you guys, adding a nice open source license would be grand. :)

Greetings, 
Leon 
(your former german-russian-something intern :P)

@iwdepop @nebillo

**Comment by kerryjj** [comment]
Hi Leon,




We'll get back to you soon on this. Just agreeing our opensourcing policies and licences internally before doing this.  



—
Kerry Jones

**Comment by cartisan** [comment]
Thank you for adding the license Kerry! @kerryjj 
You guys are good to go now @davedash @dmclain

**Comment by kerryjj** [comment]
No worries.

On 7 July 2015 at 20:39, Leon <notifications@github.com> wrote:

> Thank you for adding the license Kerry! @kerryjj
> <https://github.com/kerryjj>
> You guys are good to go now @davedash <https://github.com/davedash>
> @dmclain <https://github.com/dmclain>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/depop/sentry-pagerduty/issues/3#issuecomment-119313851>
> .
>



-- 
Kerry Jones
kerryjj@gmail.com
